FROM golang:1.24-alpine

# Set maintainer label: maintainer=[YOUR-EMAIL]
LABEL maintainer="s2410455009@students.fh-hagenberg.at"

# Set working directory: `/src`
WORKDIR /src

# Copy local file `main.go` to the working directory
# Also copy other needed files to the working directory
COPY main.go go.mod go.sum app.go model.go ./

# List items in the working directory (ls)
RUN ls

# Build the GO app as myapp binary and move it to /usr/
RUN go build -o /usr/myapp

# Expose port 8080
EXPOSE 8080

# Run the service myapp when a container of this image is launched
ENTRYPOINT ["/usr/myapp"]
