name: cdas-go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_DB_USERNAME: ${{ secrets.APP_DB_USERNAME }}
  APP_DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
  APP_DB_NAME: ${{ secrets.APP_DB_NAME }}

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Start Container (postgreSQL)
        run: docker compose up -d
      - name: Build Go
        run: go build -v ./...
      - name: Test Go
        run: go test -v ./...
  
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=lukaszando
            -Dsonar.projectKey=LukasZando_cdas_exercise2

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build -t lukzan/cdas-go:latest .
      - name: Tag Docker image
        run:
            GIT_SHA=$(git rev-parse HEAD)
            docker tag lukzan/cdas-go:latest lukzan/cdas-go:$GIT_SHA
      - name: Push Docker images
        run: docker push lukzan/cdas-go:latest && docker push lukzan/cdas-go:$GIT_SHA
