name: cdas-go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_DB_USERNAME: ${{ vars.APP_DB_USERNAME }}
  APP_DB_PASSWORD: ${{ vars.APP_DB_PASSWORD }}
  APP_DB_NAME: ${{ vars.APP_DB_NAME }}

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Start Container (postgreSQL)
        run: docker compose up -d
      - name: Build Go
        run: go build -v ./...
      - name: Test Go
        run: go test -v ./...
  
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}
