name: cdas-go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_DB_USERNAME: ${{ vars.APP_DB_USERNAME }}
  ADD_DB_PASSWORD: ${{ vars.APP_DB_PASSWORD }}
  APP_DB_NAME: ${{ vars.APP_DB_NAME }}

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
